apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: html
  namespace: devops-intermidate
spec:
  rules:
    - host: artak.test.local
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: html
                port:
                  number: 80
